<?php

$quotes = [
    '"Don’t watch the clock; do what it does. Keep going."',
    '"Small progress is still progress."',
    '"Consistency beats intensity."',
    '"Stay positive, work hard, make it happen."',
    '"Your only limit is you."',
    '"Discipline is the bridge between goals and accomplishment."',
    '"A little progress each day adds up to big results."',
    '"Dream big. Start small. Act now."',
    '"Success doesn’t come from what you do occasionally, it comes from what you do consistently."',
    '"Push yourself, because no one else is going to do it for you."',
    '"Do something today that your future self will thank you for."',
    '"Great things never come from comfort zones."',
    '"Your habits will decide your future."',
    '"Don’t stop when you’re tired. Stop when you’re done."',
    '"Progress, not perfection."',
    '"The secret of your future is hidden in your daily routine."',
    '"Small daily improvements are the key to long-term results."',
    '"Action is the foundational key to all success."',
    '"Motivation gets you started, habit keeps you going."',
    '"Fall in love with the process and the results will come."',
    '"Believe you can and you’re halfway there."',
    '"Start where you are. Use what you have. Do what you can."',
    '"Don’t limit your challenges. Challenge your limits."',
    '"It always seems impossible until it’s done."',
    '"Success is the sum of small efforts repeated day in and day out."',
    '"Doubt kills more dreams than failure ever will."',
    '"Perseverance is not a long race; it is many short races one after another."',
    '"Hard work beats talent when talent doesn’t work hard."',
    '"Every accomplishment starts with the decision to try."',
    '"Wake up with determination. Go to bed with satisfaction."',
    '"Don’t wish it were easier, wish you were better."',
    '"Your future is created by what you do today, not tomorrow."',
    '"Stay disciplined. It’s not always about motivation."',
    '"If you get tired, learn to rest, not to quit."',
    '"Winners are not people who never fail, but people who never quit."',
    '"Focus on progress, not perfection."',
    '"Big journeys begin with small steps."',
    '"Excuses don’t build habits."',
    '"One day or day one — you decide."',
    '"Success doesn’t require greatness, it requires consistency."',
];
$randomQuote = $quotes[array_rand($quotes)];
header('Content-Type: application/json');
echo json_encode(['quote' => $randomQuote]);
