<?php

$quotes = [
    '"Habits are the quiet architects of your future."',
    '"Discipline today becomes freedom tomorrow."',
    '"A single habit repeated daily shapes a lifetime of results."',
    '"Good habits are small investments with compound interest."',
    '"Your habits whisper the story of who you are becoming."',
    '"Success is never sudden; it is built on invisible habits."',
    '"Habits turn effort into autopilot progress."',
    '"You don’t rise to the level of goals; you fall to the level of habits."',
    '"Habits are stronger than motivation on your weakest days."',
    '"Tiny habits carve massive change over time."',
    '"Every habit you choose is a vote for the person you want to be."',
    '"Habits transform dreams into daily actions."',
    '"What you do daily matters more than what you do occasionally."',
    '"Strong habits carry you when willpower fades."',
    '"Habits are the bridge between today’s actions and tomorrow’s outcomes."',
    '"Your future self is shaped by the habits you keep today."',
    '"Habits decide whether obstacles break you or build you."',
    '"When motivation fails, habits remain."',
    '"Lasting success is nothing more than good habits stacked together."',
    '"Change your habits, change your life."',
    '"Small daily habits lead to monumental change."',
    '"Consistency builds what talent alone cannot."',
    '"Habits are the backbone of long-term success."',
    '"A tiny improvement each day compounds into greatness."',
    '"Your actions today are the habits of tomorrow."',
    '"Discipline is choosing what you want most over what you want now."',
    '"Habits are the silent drivers of achievement."',
    '"Master your habits, master your life."',
    '"The quality of your habits determines the quality of your future."',
    '"Daily routines shape extraordinary outcomes."',
    '"Persistent habits outweigh occasional inspiration."',
    '"What you do repeatedly defines who you become."',
    '"Habits turn intentions into results."',
    '"Success is sculpted by repeated small actions."',
    '"The right habits make the hard work effortless."',
    '"Habits are the invisible hand of progress."',
    '"Greatness grows from consistent daily habits."',
    '"Your life is a reflection of your habitual choices."',
    '"Build habits, and the results will follow."',
    '"Change your habits, change your story."',
    '"Habits are the seeds of your future success."',
    '"Consistency turns ordinary actions into extraordinary results."',
    '"Small habits done daily create unstoppable momentum."',
    '"Your daily habits determine your destiny."',
    '"Focus on habits, not outcomes."',
    '"Habits are the foundation of lasting change."',
    '"Discipline in habits builds freedom in life."',
    '"Positive habits outweigh occasional brilliance."',
    '"Every great achievement begins with a habit."',
    '"Habits make the invisible work visible over time."',
    '"Daily progress is powered by your habits."',
    '"Habits define your life more than goals ever will."',
    '"The smallest habit repeated consistently has massive impact."',
    '"Strengthen your habits, and success will follow."',
    '"Your future is written by your current habits."',
    '"Good habits feed your potential, bad habits starve it."',
    '"Habits are the bridge between dreams and reality."',
    '"Consistent actions create consistent results."',
    '"Habits build character, and character builds success."',
    '"Change starts with the habits you choose today."',
];
$randomQuote = $quotes[array_rand($quotes)];
header('Content-Type: application/json');
echo json_encode(['quote' => $randomQuote]);
